CONFIG_ENABLE_NET=y
CONFIG_ENABLE_VFS=y
CONFIG_KERNEL_ASYNC=y
CONFIG_NET_ROUTER_IP="10.255.117.16"
CONFIG_NET_STATIC_IP="10.255.117.17"
CONFIG_ENABLE_WLAN=y
# Change the following two lines to your Wi-Fi SSID and password.
CONFIG_WLAN_SSID="bluekernel"
CONFIG_WLAN_PASSWORD="88888888"
