CONFIG_ENABLE_NET=y
CONFIG_ENABLE_VFS=y
CONFIG_KERNEL_ASYNC=y
CONFIG_MAIN_THREAD_STACK_SIZE=32768
CONFIG_NET_ROUTER_IP="172.20.10.1"
CONFIG_NET_STATIC_IP="172.20.10.3"
CONFIG_ENABLE_WLAN=y
# Change the following two lines to your Wi-Fi SSID and password.
CONFIG_WLAN_SSID="王子旭的iPhone"
CONFIG_WLAN_PASSWORD="88888888"
CONFIG_GPIO=y
